name: ci

on: [push, pull_request]

permissions:
  contents: write

jobs:
  test:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - '16'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm install
          npm install cross-env --save-dev
          npm install electron --save-dev

      - name: Build the app
        run: npm run build:test

      - name: Run tests
        run: npm run test
